default: &default
  username: postgres
  password: Bleu111111
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ROR_Recipe_App_development
  username: postgres
  password: Bleu111111
  port: 5433

test:
  <<: *default
  database: ROR_Recipe_App_test
  username: postgres
  password: Bleu111111
  port: 5433

production:
  <<: *default
  database: ROR_Recipe_App_production
  # username: ROR_Recipe_App
 
